In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
X, y = load_iris(return_X_y=True)

In [4]:
X_train , X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
X_train_Scaled = scaler.fit_transform(X_train)
X_test_Scaled = scaler.transform(X_test)

In [8]:
import numpy as np

(X_train -np.mean(X_train, axis = 0)) / np.std(X_train, axis = 0)

array([[-0.5513382 ,  2.08622478, -1.18252406, -1.06191815],
       [-0.43382384,  2.82982965, -1.35301211, -1.32962861],
       [ 0.50629103, -0.64032642,  0.74967384,  0.41048937],
       [-0.43382384, -1.38393129,  0.12455099,  0.14277891],
       [-1.49145308,  0.35114674, -1.35301211, -1.32962861],
       [-1.37393872,  0.35114674, -1.23935341, -1.32962861],
       [-0.19879513, -0.64032642,  0.18138034,  0.14277891],
       [ 0.74131975, -0.14458984,  0.80650319,  1.07976552],
       [ 0.62380539,  0.35114674,  0.40869774,  0.41048937],
       [-1.13891   , -0.14458984, -1.35301211, -1.32962861],
       [ 1.21137719,  0.10327845,  0.92016189,  1.21362075],
       [-0.31630948, -1.38393129,  0.06772164, -0.12493155],
       [-1.7264818 ,  0.35114674, -1.40984146, -1.32962861],
       [ 0.38877667,  0.84688332,  0.92016189,  1.48133121],
       [-1.02139564, -0.14458984, -1.23935341, -1.32962861],
       [-0.66885256,  1.5904882 , -1.29618276, -1.32962861],
       [ 0.38877667, -0.

In [7]:
X_train_Scaled

array([[-0.5513382 ,  2.08622478, -1.18252406, -1.06191815],
       [-0.43382384,  2.82982965, -1.35301211, -1.32962861],
       [ 0.50629103, -0.64032642,  0.74967384,  0.41048937],
       [-0.43382384, -1.38393129,  0.12455099,  0.14277891],
       [-1.49145308,  0.35114674, -1.35301211, -1.32962861],
       [-1.37393872,  0.35114674, -1.23935341, -1.32962861],
       [-0.19879513, -0.64032642,  0.18138034,  0.14277891],
       [ 0.74131975, -0.14458984,  0.80650319,  1.07976552],
       [ 0.62380539,  0.35114674,  0.40869774,  0.41048937],
       [-1.13891   , -0.14458984, -1.35301211, -1.32962861],
       [ 1.21137719,  0.10327845,  0.92016189,  1.21362075],
       [-0.31630948, -1.38393129,  0.06772164, -0.12493155],
       [-1.7264818 ,  0.35114674, -1.40984146, -1.32962861],
       [ 0.38877667,  0.84688332,  0.92016189,  1.48133121],
       [-1.02139564, -0.14458984, -1.23935341, -1.32962861],
       [-0.66885256,  1.5904882 , -1.29618276, -1.32962861],
       [ 0.38877667, -0.

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_Scaled = scaler.fit_transform(X_train)
X_test_Scaled = scaler.transform(X_test)

X_train_Scaled

array([[0.30555556, 0.86363636, 0.10344828, 0.125     ],
       [0.33333333, 1.        , 0.05172414, 0.04166667],
       [0.55555556, 0.36363636, 0.68965517, 0.58333333],
       [0.33333333, 0.22727273, 0.5       , 0.5       ],
       [0.08333333, 0.54545455, 0.05172414, 0.04166667],
       [0.11111111, 0.54545455, 0.0862069 , 0.04166667],
       [0.38888889, 0.36363636, 0.51724138, 0.5       ],
       [0.61111111, 0.45454545, 0.70689655, 0.79166667],
       [0.58333333, 0.54545455, 0.5862069 , 0.58333333],
       [0.16666667, 0.45454545, 0.05172414, 0.04166667],
       [0.72222222, 0.5       , 0.74137931, 0.83333333],
       [0.36111111, 0.22727273, 0.48275862, 0.41666667],
       [0.02777778, 0.54545455, 0.03448276, 0.04166667],
       [0.52777778, 0.63636364, 0.74137931, 0.91666667],
       [0.19444444, 0.45454545, 0.0862069 , 0.04166667],
       [0.27777778, 0.77272727, 0.06896552, 0.04166667],
       [0.52777778, 0.40909091, 0.55172414, 0.5       ],
       [0.66666667, 0.45454545,

In [12]:
X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis=0)

(X_train - X_min) / (X_max - X_min)

array([[0.30555556, 0.86363636, 0.10344828, 0.125     ],
       [0.33333333, 1.        , 0.05172414, 0.04166667],
       [0.55555556, 0.36363636, 0.68965517, 0.58333333],
       [0.33333333, 0.22727273, 0.5       , 0.5       ],
       [0.08333333, 0.54545455, 0.05172414, 0.04166667],
       [0.11111111, 0.54545455, 0.0862069 , 0.04166667],
       [0.38888889, 0.36363636, 0.51724138, 0.5       ],
       [0.61111111, 0.45454545, 0.70689655, 0.79166667],
       [0.58333333, 0.54545455, 0.5862069 , 0.58333333],
       [0.16666667, 0.45454545, 0.05172414, 0.04166667],
       [0.72222222, 0.5       , 0.74137931, 0.83333333],
       [0.36111111, 0.22727273, 0.48275862, 0.41666667],
       [0.02777778, 0.54545455, 0.03448276, 0.04166667],
       [0.52777778, 0.63636364, 0.74137931, 0.91666667],
       [0.19444444, 0.45454545, 0.0862069 , 0.04166667],
       [0.27777778, 0.77272727, 0.06896552, 0.04166667],
       [0.52777778, 0.40909091, 0.55172414, 0.5       ],
       [0.66666667, 0.45454545,