# **Advanced Array Manipulation**

### Stacking Arrays

In [3]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])


In [7]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Splitting Arrays

In [10]:
c = np.arange(16).reshape(4,4)

In [12]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [23]:
# vsplit and split with axis = 0 are the same.

np.split(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]