# **Array Operations**

In [1]:
import numpy as np

# Arithmetic operations

*Note*: size of the array must be same for both the arrays

In [4]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [5]:
a1 + a2

array([5, 7, 9])

In [7]:
a1 - a2

array([-3, -3, -3])

In [8]:
a1 * a2

array([ 4, 10, 18])

In [9]:
a1 / a2

array([0.25, 0.4 , 0.5 ])

In [10]:
a1 // a2

array([0, 0, 0])

In [11]:
a1 ** a2

array([  1,  32, 729])