# **Array Operations**

In [32]:
import numpy as np

# Arithmetic operations

*Note*: size of the array must be same for both the arrays

In [33]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [34]:
a1 + a2

array([5, 7, 9])

In [35]:
a1 - a2

array([-3, -3, -3])

In [36]:
a1 * a2

array([ 4, 10, 18])

In [37]:
a1 / a2

array([0.25, 0.4 , 0.5 ])

In [38]:
a1 // a2

array([0, 0, 0])

In [39]:
a1 ** a2

array([  1,  32, 729])

## Array Broadcasting

In [40]:
# Array broadcasting works on the principle of the smaller array being "broadcast" across the larger array so that they have compatible shapes. This allows for element-wise operations to be performed on arrays of different sizes and shapes without the need for explicit replication of data.

# we can add a scalar value to an array, and the scalar will be broadcasted to each element of the array.

In [41]:
l = [10,20,30,40]

arr = np.array(l)

In [42]:
arr + 10

array([20, 30, 40, 50])

In [43]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [45]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

## Deep and Shallow Copy

In [62]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
slice = a[:5]
slice *10

array([10, 20, 30, 40, 50])

In [57]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
b = a.copy()
b[0] = 99
b



array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [61]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# matrix operations

In [64]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]]) 

In [65]:
A

array([[1, 2],
       [3, 4]])

In [66]:
B

array([[5, 6],
       [7, 8]])

In [68]:
A @ B

array([[19, 22],
       [43, 50]])

In [69]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [71]:
# Transpose of a matrix

A

array([[1, 2],
       [3, 4]])

In [72]:
A.T

array([[1, 3],
       [2, 4]])