# **Importing NumPy**

In [1]:
import numpy as np

## **numpy indexing and slicing and slicing of vectors**

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
# indexing

arr[9]

np.int64(20)

In [4]:
# slicing

# format (start:stop:step)

arr[0:5]

array([11, 12, 13, 14, 15])

## **numpy indexing and slicing and slicing of matrix**

In [5]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [6]:
arr[0]

array([1, 2, 3, 4, 5])

In [7]:
#finding 1

arr[0,0]

np.int64(1)

In [8]:
#finding 5

arr[0,4]

np.int64(5)

In [9]:
# finding 30

arr[5,4]

np.int64(30)

In [10]:
# slicing

slice = arr[0:2,1:3]

slice

array([[2, 3],
       [7, 8]])

In [11]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
slice = arr[3:,3:]

slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [13]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## **Boolean indexing**


**note** : ~ *while doing the boolean indexing we must keep in mind that both the array and the boolean index must be of the same shape*

In [14]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
bool_index = arr % 2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [16]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])