# **`NumPy Arrays`**

---

## **Difference Between a list and array in Python**

### 1. Type of Elements:
 - List: A list can contain elements of different data types (e.g., integers,
   strings, floats, etc.).
 - Array: An array typically contains elements of the same data type (e.g.,
   all integers or all floats).

### 2. Performance:
 - List: Lists are more flexible but can be slower for large datasets due to
   their dynamic nature.
 - Array: Arrays are more efficient for numerical operations and can be faster
   for large datasets, especially when using libraries like NumPy.

### 3. Functionality:
 - List: Lists have a wide range of built-in methods for manipulation (e.g.,
   append, remove, etc.).
 - Array: Arrays have fewer built-in methods but can be manipulated using
   libraries like NumPy, which provide extensive functionality for array operations.


----

## **Importing numpy**

In [1]:
import numpy as np

## **Basic Array creation**

In [10]:
# Array
arr = np.array([1, 2, 3])
print(arr)

# List 

lst = [1, 2, 3, "Hello"]
print(lst)

[1 2 3]
[1, 2, 3, 'Hello']


---
### **Note :** ~ *`We can convert a hetrogeneous list to a numpy array but it will convert all the elements to the same data type. In this case, it will convert all the elements to string data type.`*
---

In [ ]:
lst = np.array(lst)
lst

array(['1', '2', '3', 'Hello'], dtype='<U21')

## **Dimensions and multidimensional arrays**

---

### *`Verticals are the columns`*
### *`Horizontals are the rows`*

**Example matrix**:

```text
[
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]
```
-1,4,7 is a column

-1,2,3 is a row

---

In [12]:
l = [[1,2,3], [4,5,6], [7,8,9]]
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [13]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Array Generation Function**

---
### *`format: (start , stop, step)`*
---

In [19]:
arr = np.arange(1, 10,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
# Single dimension array of zeros
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# Multi dimension array of zeros

arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# array of ones

arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## **Lin space**

---



### *`format: (start , stop, step)`*


### All the values in the arrays will be linearly spaced from each other.
---

In [30]:
arr = np.linspace(1, 5, 10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
arr = np.linspace(1, 5, 100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

## **Random Generation Function**

---
 ### ```Random module is an inbuilt functions which gets imported, while importing the numpy library.```
---

In [ ]:
np.random.rand(10)

array([0.15127659, 0.92846242, 0.18337807, 0.61011066, 0.997158  ,
       0.72254296, 0.69720062, 0.05345071, 0.8316244 , 0.44043411])

In [39]:
np.random.randint(1, 7,10)

array([6, 5, 5, 6, 5, 2, 6, 3, 2, 6])

## **Array Attributes**

---
### Notes:~ Arrays have a lot of other attributes but these are the most common attributes used in a normal work flow.

#### *size* : It tells the amount of values/elements.

#### *shape* : It tells the dimension.

#### *dtype* : It tells the datatype of the array.

---

In [43]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr.shape

(3, 3)

In [45]:
arr.size

9

In [46]:
arr.dtype

dtype('int64')

## **Array Methods**

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Minimum
print(arr.min())

1


In [ ]:
# Maximum
print(arr.max())

9


In [56]:
# this is the sum using the inbuilt function of python
print(arr.sum())

45


---
### **Note**:

#### `Row is the` **`1`** `Axis`
#### `Column is the` **`0`** `Axis`
---

In [61]:
# this is the sum using axis argument

print(arr.sum(axis=0)) # column wise sum
print(arr.sum(axis=1)) # row wise sum

[12 15 18]
[ 6 15 24]


In [ ]:
# Mean/Average
print(np.mean(arr))

5.0


In [65]:
# Standard Deviation
print(np.std(arr))

2.581988897471611


In [68]:
# Argmin and Argmax
print(arr.argmin())
print(arr.argmax())

# this is used to retrieve the poisition of the minimum and maximum value in the array. It returns the index of the minimum and maximum value in the array.

0
8


## **Reshaping and Resizing**

In [70]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# The reshape function takes in 2 arguments

### *reshape(a,b)*

a is rows and
b is columns

In [76]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])